name: build-test-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cp example.env .env
          docker-compose up -d
      - name: Test
        run: |
          docker container ls
          docker exec covidtest_app pytest --cov=.
  deploy:
    needs: build
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Triggering webhook
        uses: wei/curl@v1
        with:
          args: "https://webhooks.covidtest-hd.de/hooks/deployment?token=${{ secrets.WEBHOOK_KEY }}"