name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cp example.env .env
          docker-compose build
      - name: Test
        run: docker exec -it covidtest_app python manage.py test
        
